name: Dummy for test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-env:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
  call-workflow1:
    needs: [setup-env]
    uses: ./.github/workflows/test1.yaml
  call-workflow2:
    needs: [call-workflow1]
    uses: ./.github/workflows/test2.yaml
